### ISSUE TITLE
Set up icons

### ISSUE THREAD

**Issue by stesvis** [stesvis/XamlDemo#2]
I don't know what to suggest here, but basically we need to be able to add a bunch of icons to the app, as vectors, to allow us to use them anywhere needed, without having to create all the different size versions for each icon.
Grial UIKit is the example.

I don't know where to get the icons from, but if we could use the font-awesome icons it would be great.
https://www.flaticon.com/packs/font-awesome
https://www.iconfinder.com/iconsets/font-awesome

**Comment by rolestar1016** [comment]
Okay, got the point.

**Comment by stesvis** [comment]
Done

**Comment by rolestar1016** [comment]
Hi
